### ISSUE TITLE
Array Enumerator infinitely loops

### ISSUE THREAD

**Issue by frankracis-litmos** [sharkadi-a/JsonEasyNavigation#7]
The `readonly` on this line prevents the inner enumerator from changing, causing it to infinitely loop.

https://github.com/sharkadi-a/JsonEasyNavigation/blob/a8ac197e48131ae3b0aacac0076733a6e8784a4f/src/JsonEasyNavigation/ArrayEnumeratorWrapper.cs#L10

Apparently, if a readonly field is a struct, not only are you not allowed to reassign the value, it's not allowed to change its own state.

**Comment by sharkadi-a** [comment]
Thank you for bringing my attention to that! I will try to see the issue later.
